# Generated by Django 5.2.17 on 2026-10-03 11:26

import club.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('kind', models.CharField(choices=[('apero', 'Apéro'), ('dinner', 'Dîner / soirée'), ('conference', 'Conférence'), ('visit', 'Visite')], max_length=12, verbose_name='type')),
                ('starts_at', models.DateTimeField(verbose_name='début')),
                ('location', models.CharField(max_length=150, verbose_name='lieu')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('has_seating', models.BooleanField(default=False, verbose_name='repas assis (tables tournantes)')),
            ],
            options={
                'verbose_name': 'événement',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(max_length=8)),
                ('category', models.CharField(choices=[('hobby', 'Loisirs'), ('valais', 'Valais & terroir'), ('culture', 'Culture & curiosités'), ('work', 'Vie de bureau')], max_length=10)),
                ('label_fr', models.CharField(max_length=80)),
                ('label_de', models.CharField(blank=True, max_length=80)),
                ('label_en', models.CharField(blank=True, max_length=80)),
                ('icebreaker_fr', models.CharField(blank=True, max_length=200)),
                ('icebreaker_de', models.CharField(blank=True, max_length=200)),
                ('icebreaker_en', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('company', models.CharField(max_length=120, verbose_name='entreprise')),
                ('job_title', models.CharField(max_length=120, verbose_name='fonction')),
                ('sector', models.CharField(choices=[('construction', 'Construction & immobilier'), ('finance', 'Banque, finance & assurance'), ('tourism', 'Tourisme & hôtellerie'), ('wine_food', 'Vins & agroalimentaire'), ('energy', 'Énergie & environnement'), ('industry', 'Industrie & artisanat'), ('tech', 'Tech & digital'), ('health', 'Santé'), ('services', 'Conseil, juridique & fiduciaire'), ('retail', 'Commerce & distribution'), ('transport', 'Transport & logistique'), ('media', 'Communication & médias')], max_length=20, verbose_name='secteur')),
                ('region', models.CharField(blank=True, max_length=80, verbose_name='région')),
                ('speaks_fr', models.BooleanField(default=True, verbose_name='parle français')),
                ('speaks_de', models.BooleanField(default=False, verbose_name='parle allemand')),
                ('speaks_en', models.BooleanField(default=False, verbose_name='parle anglais')),
                ('member_since', models.PositiveSmallIntegerField(verbose_name='membre depuis (année)')),
                ('is_founder', models.BooleanField(default=False, verbose_name='membre fondateur')),
                ('fun_fact', models.CharField(blank=True, max_length=200, verbose_name='anecdote')),
                ('talk_to_me_about', models.CharField(blank=True, max_length=120, verbose_name='parle-moi de…')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('visible_in_directory', models.BooleanField(default=True, verbose_name="visible dans l'album")),
                ('onboarding_done', models.BooleanField(default=False)),
                ('qr_token', models.CharField(default=club.models.new_qr_token, editable=False, max_length=32, unique=True)),
                ('referral_code', models.CharField(default=club.models.new_referral_code, editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membre',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InvitationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('company', models.CharField(max_length=120, verbose_name='entreprise')),
                ('job_title', models.CharField(max_length=120, verbose_name='fonction')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='club.member')),
            ],
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.PositiveSmallIntegerField(default=3)),
                ('table_size', models.PositiveSmallIntegerField(default=6)),
                ('new_pairs', models.PositiveIntegerField(default=0)),
                ('repeated_pairs', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plan', to='club.event')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('shared_likes', models.JSONField(default=list)),
                ('shared_dislikes', models.JSONField(default=list)),
                ('cross_sector', models.BooleanField(default=False)),
                ('welcomes_newcomer', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='club.event')),
                ('member_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='club.member')),
                ('member_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='club.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'member_a', 'member_b'), name='unique_match'), models.CheckConstraint(condition=models.Q(('member_a__lt', models.F('member_b'))), name='match_ordered_pair')],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('qr', 'Scan QR'), ('admin', 'Ajout admin'), ('seed', 'Données de démo')], default='qr', max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='club.event')),
                ('member_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='club.member')),
                ('member_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='club.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member_a', 'member_b'), name='unique_connection'), models.CheckConstraint(condition=models.Q(('member_a__lt', models.F('member_b'))), name='connection_ordered_pair')],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'Je viens'), ('no', 'Je ne viens pas')], max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='club.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='club.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='unique_rsvp')],
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_index', models.PositiveSmallIntegerField()),
                ('table_number', models.PositiveSmallIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='club.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='club.seatingplan')),
            ],
            options={
                'ordering': ['round_index', 'table_number'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'round_index', 'member'), name='unique_seat_per_round')],
            },
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('like', "J'adore"), ('neutral', 'Bof'), ('dislike', 'Je déteste')], max_length=8)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='club.member')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='club.tag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'tag'), name='unique_member_tag')],
            },
        ),
    ]
