# Generated by Django 5.2.17 on 2026-10-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'verbose_name': 'rencontre'},
        ),
        migrations.AlterModelOptions(
            name='invitationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': "demande d'invitation", 'verbose_name_plural': "demandes d'invitation"},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'rencontre proposée', 'verbose_name_plural': 'rencontres proposées'},
        ),
        migrations.AlterModelOptions(
            name='membertag',
            options={'verbose_name': 'affinité du membre', 'verbose_name_plural': 'affinités du membre'},
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={'verbose_name': 'inscription'},
        ),
        migrations.AlterModelOptions(
            name='seatingplan',
            options={'verbose_name': 'plan de tables', 'verbose_name_plural': 'plans de tables'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'slug'], 'verbose_name': 'affinité'},
        ),
        migrations.AddField(
            model_name='event',
            name='has_bingo',
            field=models.BooleanField(default=False, help_text="Pour un apéro debout : chaque inscrit reçoit une grille « Trouve quelqu'un qui… » qu'il remplit en scannant des QR codes. Rien à préparer.", verbose_name='bingo des rencontres'),
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('de', 'Deutsch'), ('en', 'English')], default='fr', max_length=2, verbose_name='langue'),
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_request', to='club.member', verbose_name='compte créé'),
        ),
        migrations.AddField(
            model_name='invitationrequest',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='e-mail de bienvenue envoyé le'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text="Visible par les membres sur la page de l'événement. Astuce : le texte en français, puis en allemand après « · ».", verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='has_seating',
            field=models.BooleanField(default=False, help_text="Pour un dîner assis : l'équipe génère un plan où chacun change de table à chaque service (Tableau de bord → Préparer).", verbose_name='repas assis (tables tournantes)'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='reçue le'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='club.member', verbose_name='parrain ou marraine'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='new', help_text="« Acceptée » crée le compte du nouveau membre et lui envoie l'e-mail de bienvenue pour choisir son mot de passe.", max_length=10, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_founder',
            field=models.BooleanField(default=False, help_text='Membre depuis la création du Club : bordure dorée sur sa carte.', verbose_name='membre fondateur'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_since',
            field=models.PositiveSmallIntegerField(help_text="Année d'entrée au Club. Elle donne le rang : nouvelle recrue la première année, pilier après 5 ans.", verbose_name='membre depuis (année)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='onboarding_done',
            field=models.BooleanField(default=False, help_text='Coché automatiquement quand le membre a choisi ses affinités.', verbose_name='profil complété'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sector',
            field=models.CharField(choices=[('construction', 'Construction & immobilier'), ('finance', 'Banque, finance & assurance'), ('tourism', 'Tourisme & hôtellerie'), ('wine_food', 'Vins & agroalimentaire'), ('energy', 'Énergie & environnement'), ('industry', 'Industrie & artisanat'), ('tech', 'Tech & digital'), ('health', 'Santé'), ('services', 'Conseil, juridique & fiduciaire'), ('retail', 'Commerce & distribution'), ('transport', 'Transport & logistique'), ('media', 'Communication & médias'), ('other', 'Autre secteur')], max_length=20, verbose_name='secteur'),
        ),
        migrations.AlterField(
            model_name='member',
            name='visible_in_directory',
            field=models.BooleanField(default=True, help_text='Décoché : seuls les membres déjà rencontrés voient sa carte.', verbose_name="visible dans l'album"),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('yes', 'Je viens'), ('no', 'Je ne viens pas')], max_length=3, verbose_name='réponse'),
        ),
        migrations.CreateModel(
            name='BingoSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('like', 'adore'), ('dislike', 'déteste'), ('language', 'parle'), ('sector', 'secteur'), ('rank', 'rang'), ('region', 'région'), ('joker', 'joker')], max_length=10)),
                ('value', models.CharField(blank=True, max_length=80)),
                ('found_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_squares', to='club.event')),
                ('found', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='club.member')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_squares', to='club.member')),
            ],
            options={
                'verbose_name': 'case de bingo',
                'verbose_name_plural': 'cases de bingo',
                'ordering': ['event', 'player', 'position'],
                'constraints': [models.UniqueConstraint(fields=('event', 'player', 'position'), name='unique_bingo_square'), models.UniqueConstraint(condition=models.Q(('found__isnull', False)), fields=('event', 'player', 'found'), name='one_bingo_square_per_person')],
            },
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('company', models.CharField(max_length=120, verbose_name='entreprise')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='fonction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='club.event', verbose_name='événement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='club.member', verbose_name='membre remplacé')),
            ],
            options={
                'verbose_name': 'remplaçant·e',
                'verbose_name_plural': 'remplaçant·e·s',
                'ordering': ['event', 'last_name', 'first_name'],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='one_substitute_per_member')],
            },
        ),
    ]
