# Generated by Django 5.2.17 on 2026-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_admin_help_bingo_substitutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_de',
            field=models.TextField(blank=True, help_text="Facultatif : vide, le texte français s'affiche.", verbose_name='description (allemand)'),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(blank=True, help_text="Facultatif : vide, le texte français s'affiche.", verbose_name='description (anglais)'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_de',
            field=models.CharField(blank=True, help_text="Facultatif : vide, le texte français s'affiche.", max_length=150, verbose_name='lieu (allemand)'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, help_text="Facultatif : vide, le texte français s'affiche.", max_length=150, verbose_name='lieu (anglais)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_de',
            field=models.CharField(blank=True, help_text="Facultatif : vide, le texte français s'affiche.", max_length=150, verbose_name='titre (allemand)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(blank=True, help_text="Facultatif : vide, le texte français s'affiche.", max_length=150, verbose_name='titre (anglais)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text="Visible par les membres sur la page de l'événement.", verbose_name='description'),
        ),
    ]
