# Generated by Django 5.2.17 on 2026-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_event_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='has_bingo',
            field=models.BooleanField(default=False, help_text="Préparation du bingo : le modèle est disponible, le jeu n'est pas encore activé dans l'application.", verbose_name='bingo des rencontres'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='new', help_text="Suivi de la demande. La création du compte et l'envoi de l'accès sont encore gérés séparément par l'équipe.", max_length=10, verbose_name='statut'),
        ),
    ]
