# Generated by Django 5.2.17 on 2026-10-03 16:50

from django.db import migrations, models


def assign_demo_portraits(apps, schema_editor):
    Member = apps.get_model("club", "Member")
    for email, key in (("camille.rey@example.com", "camille"),
                       ("lukas.imboden@example.com", "lukas"),
                       ("joelle.luisier@example.com", "joelle")):
        Member.objects.using(schema_editor.connection.alias).filter(user__email=email, demo_photo_key="").update(demo_photo_key=key)


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_honest_admin_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='demo_photo_key',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.RunPython(assign_demo_portraits, migrations.RunPython.noop),
    ]
