# Generated by Django 5.2.17 on 2026-10-03 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_demo_portraits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to='club.member')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_about', to='club.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'target'), name='unique_personal_note'), models.CheckConstraint(condition=models.Q(('owner', models.F('target')), _negated=True), name='personal_note_not_self')],
            },
        ),
    ]
