# Generated by Django 5.2.17 on 2026-10-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_personal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='member_photos/'),
        ),
    ]
