# Generated by Django 5.2.17 on 2026-10-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_private_portraits'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admitted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='digest_teaser',
            field=models.CharField(blank=True, max_length=120, verbose_name='Accroche pour le récapitulatif'),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('de', 'Allemand'), ('en', 'Anglais')], max_length=2, verbose_name='Langue des emails'),
        ),
        migrations.AlterField(
            model_name='invitationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Nouvelle'), ('contacted', 'Contactée'), ('accepted', 'Acceptée'), ('declined', 'Refusée')], default='new', help_text="L'action d'acceptation crée le compte. L'accès est envoyé par lien de connexion, sans choix de mot de passe.", max_length=10, verbose_name='statut'),
        ),
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_announcements', models.BooleanField(default=True, verbose_name='Annonces des événements')),
                ('event_reminders', models.BooleanField(default=True, verbose_name='Relances sans réponse')),
                ('monthly_digest', models.BooleanField(default=False, verbose_name='Récapitulatif mensuel des nouveaux membres')),
                ('allow_member_spotlight', models.BooleanField(default=False, verbose_name='Autoriser ma présentation dans le récapitulatif')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to='club.member')),
            ],
        ),
    ]
