# Generated by Django 5.2.17 on 2026-10-03 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def preserve_existing_events(apps, schema_editor):
    Event = apps.get_model("club", "Event")
    Event.objects.using(schema_editor.connection.alias).all().update(is_published=True)


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_membership_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False, editable=False, verbose_name='Publié'),
        ),
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin des réponses'),
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'Bienvenue'), ('event_announcement', 'Annonce'), ('event_reminder', 'Relance'), ('new_members', 'Nouveaux membres')], max_length=24)),
                ('scope_key', models.CharField(max_length=120, unique=True)),
                ('month', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_campaigns', to='club.event')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.invitationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sending', "En cours d'envoi"), ('sent', 'Accepté par SMTP'), ('skipped', 'Ignoré'), ('failed', 'Échec confirmé'), ('uncertain', 'Résultat incertain')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=40)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='club.notificationcampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='club.member')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notification_due')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'recipient'), name='unique_campaign_recipient')],
            },
        ),
        migrations.RunPython(preserve_existing_events, migrations.RunPython.noop),
    ]
