# Generated by Django 5.2.17 on 2026-10-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_event_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digest_entries', to='club.notificationcampaign')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest_entry', to='club.member')),
            ],
        ),
    ]
