# Generated by Django 5.2.17 on 2026-10-03 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_monthly_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='guest_access_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='kind',
            field=models.CharField(choices=[('member', 'Membre'), ('guest', 'Invité')], default='member', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationcampaign',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.substitute'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='substitute',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_invitations', to='club.member'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('de', 'Allemand'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue des emails'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='speaks_de',
            field=models.BooleanField(default=False, verbose_name='parle allemand'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='speaks_en',
            field=models.BooleanField(default=False, verbose_name='parle anglais'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='speaks_fr',
            field=models.BooleanField(default=True, verbose_name='parle français'),
        ),
        migrations.AddField(
            model_name='substitute',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('cancelled', 'Annulé')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationcampaign',
            name='kind',
            field=models.CharField(choices=[('welcome', 'Bienvenue'), ('event_announcement', 'Annonce'), ('event_reminder', 'Relance'), ('new_members', 'Nouveaux membres'), ('guest_access', 'Accès invité')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='substitute',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('event', 'guest'), name='unique_approved_event_guest'),
        ),
        migrations.AddConstraint(
            model_name='substitute',
            constraint=models.CheckConstraint(condition=models.Q(('guest__isnull', True), models.Q(('guest', models.F('member')), _negated=True), _connector='OR'), name='substitute_not_principal'),
        ),
    ]
