# Generated by Django 5.2.17 on 2026-10-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_temporary_substitutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('de', 'Allemand'), ('en', 'Anglais')], max_length=2, verbose_name='Langue des communications'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('de', 'Allemand'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue des communications'),
        ),
    ]
