# Generated by Django 5.2.17 on 2026-10-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_communication_language_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='has_bingo',
            field=models.BooleanField(default=False, help_text="Pour un apéro debout : chaque inscrit reçoit une grille « Trouve quelqu'un qui… » qu'il remplit en scannant des QR codes. Rien à préparer.", verbose_name='bingo des rencontres'),
        ),
    ]
