# Generated by Django 5.2.17 on 2026-10-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_bingo_live'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('emoji', models.CharField(max_length=8)),
                ('label_fr', models.CharField(max_length=80)),
                ('label_de', models.CharField(blank=True, max_length=80)),
                ('label_en', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': "thème d'entraide",
                'verbose_name_plural': "thèmes d'entraide",
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='synergies',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='MemberExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offer', 'Je peux aider sur'), ('need', 'Je cherche')], max_length=8)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='club.expertise')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_links', to='club.member')),
            ],
            options={
                'verbose_name': "thème d'entraide du membre",
                'verbose_name_plural': "thèmes d'entraide du membre",
                'constraints': [models.UniqueConstraint(fields=('member', 'expertise', 'kind'), name='unique_member_expertise')],
            },
        ),
    ]
